title: Improved and Extended Multilocus Sequence Typing (MLST) Scheme for Streptomyces reveals Complex Taxonomic Structure
theme: jekyll-theme-cayman
plugins:
  - jemoji
github:
  is_project_page: false

topnav_title: University of Strathclyde