title: Improved and Extended Multilocus Sequence Typing (MLST) Scheme for Streptomyces reveals Complex Taxonomic Structure
subtitle: Angelika Kiepas, Prof Paul A Hoskisson, Dr Leighton Pritchard
subtitle: Strathclyde Insitute of Pharmacy and Biomedical Sciences, University of Strathclyde, 161 Cathedral Street, Glasgow G4 0RE, Scotland, UK
theme: jekyll-theme-cayman
plugins:
  - jemoji