title: Improved and Extended Multilocus Sequence Typing (MLST) Scheme for Streptomyces reveals Complex Taxonomic Structure
subtitle: Angelika Kiepas, Prof Paul A Hoskisson, Dr Leighton Pritchard
theme: jekyll-theme-cayman
plugins:
  - jemoji
github:
  is_project_page: false